import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";

const graphcms = new GraphQLClient(process.env.GRAPHQL_CLIENT || "");

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  try {
    const { posts }: any = await graphcms.request(QUERY);

    return {
      props: {
        posts,
      },
      revalidate: 10,
    };
  } catch (error) {
    console.log(error);
  }

  return {
    props: {},
  };
}

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container max-w-4xl m-auto flex flex-col sm:flex-row items-center justify-center flex-wrap min-h-screen">
        {posts.map((post: any) => (
          <BlogCard
            key={post.id}
            slug={post.slug}
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.datePublished}
          />
        ))}
      </main>
    </>
  );
}
