import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";

const graphcms = new GraphQLClient(process.env.GRAPHQL_CLIENT || "");

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  try {
    const { posts }: any = await graphcms.request(QUERY);

    return {
      props: {
        posts,
      },
      revalidate: 60,
    };
  } catch (error) {
    console.log(error);
  }

  return {
    props: {},
  };
}

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Chalet Blog</title>
        <meta
          name="Blog para compartilhar meus estudos e progressão dentro do desenvolvimento de software."
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-[#0B1120] h-20 flex items-center px-5 sticky top-0">
        <span className="text-slate-300 text-2xl font-bold">CHALET&apos;S</span>
      </header>
      <main className="container max-w-6xl m-auto py-14 flex flex-col sm:flex-row items-center justify-center flex-wrap min-h-screen">
        {posts.map((post: any) => (
          <BlogCard
            key={post.id}
            slug={post.slug}
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.datePublished}
          />
        ))}
      </main>
    </>
  );
}
